---
  team_mappings:
    Engineering: 0
    Data: 10
    Product: 20
    Design: 30
    Marketing: 40
    Outreach: 50
    Community Support: 60
    Integrity: 70
    Communications: 80
    Operations: 90
    Exec: 110
  # specialty_mappings:
  #   Backend: 0
  #   ST: 50
  #   Frontend: 10
  #   Mobile: 20
  weights:
    days_here: 0.2
    team: 0.9
    # specialty: 0.1
  min_lunch_group_size: 5
  min_group_score: 0.0001
  time_decay_constant: 80.0
  # hierarchy:
  #   Bossy McBossface:
  #     Employee McEmployeeface:
  #     Coworker McCoworkerface:
  #   Intern:
